/*

- Copyright © 2026 Castellese Brian Vincenzo.
- Licensed under the PolyForm Noncommercial License 1.0.0.
- Commercial use and resale require separate written permission.
- See LICENSE for the complete terms.

*/

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "Player/MT2PlayerTypes.h"
#include "World/MT2MapAttributes.h"
#include "MT2MapPresentationActor.generated.h"

class UTexture2D;
class UAudioComponent;
class UDirectionalLightComponent;
class UExponentialHeightFogComponent;
class USceneComponent;
class USkyLightComponent;
class USoundBase;

USTRUCT(BlueprintType)
struct METIN2_API FMT2MapEnvironmentSettings
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Environment")
	FString SourceReference;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Environment|Light")
	bool bDirectionalLightEnabled = false;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Environment|Light")
	FVector LightDirection = FVector(0.5f, 0.5f, -0.5f);

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Environment|Light")
	FLinearColor DirectionalLightColor = FLinearColor::White;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Environment|Light", meta = (ClampMin = "0.0"))
	float DirectionalLightIntensity = 3.141593f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Environment|Light")
	FLinearColor AmbientLightColor = FLinearColor::Black;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Environment|Light", meta = (ClampMin = "0.0"))
	float AmbientLightIntensity = 0.25f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Environment|Fog")
	bool bFogEnabled = false;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Environment|Fog", meta = (ClampMin = "0.0"))
	float FogNearDistance = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Environment|Fog", meta = (ClampMin = "0.0"))
	float FogFarDistance = 20000.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Environment|Fog")
	FLinearColor FogColor = FLinearColor(0.5f, 0.5f, 0.5f);

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Environment|Fog", meta = (ClampMin = "0.0"))
	float FogDensity = 0.2f;
};

USTRUCT(BlueprintType)
struct METIN2_API FMT2MinimapTile
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Minimap")
	FIntPoint Cell = FIntPoint::ZeroValue;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Minimap")
	TSoftObjectPtr<UTexture2D> Texture;
};

USTRUCT(BlueprintType)
struct METIN2_API FMT2FullMapNpcMarker
{
	GENERATED_BODY()

	UPROPERTY(BlueprintReadOnly, Category = "Map")
	FVector Location = FVector::ZeroVector;

	UPROPERTY(BlueprintReadOnly, Category = "Map")
	FString DisplayName;

	// Mob vnum, so the full map can tell whether an active quest is pointing at this NPC. 0 for
	// non-mob markers such as portals.
	UPROPERTY(BlueprintReadOnly, Category = "Map")
	int32 Vnum = 0;
};

// Level-owned presentation data generated by the map importer. Keeping this separate from the
// server-only spawn actor makes the minimap available on clients without replicating static data.
UCLASS(BlueprintType)
class METIN2_API AMT2MapPresentationActor : public AActor
{
	GENERATED_BODY()

public:
	AMT2MapPresentationActor();
	virtual void OnConstruction(const FTransform& Transform) override;
	virtual void BeginPlay() override;
	virtual void EndPlay(const EEndPlayReason::Type EndPlayReason) override;

	void Configure(const FString& InMapId, int32 InMapIndex, const FIntPoint& InMapCells,
		const FVector2D& InWorldMin, const FVector2D& InWorldMax,
		const TArray<FMT2MinimapTile>& InMinimapTiles,
		const FVector2D& InDefaultTownSpawn = FVector2D::ZeroVector,
		const TArray<FVector2D>& InEmpireTownSpawns = {});
	void ConfigureEnvironment(const FMT2MapEnvironmentSettings& InEnvironment);

	UFUNCTION(BlueprintPure, Category = "Map|Spawn")
	FVector2D GetTownSpawn(EMT2Empire Empire) const;

	UFUNCTION(BlueprintPure, Category = "Map")
	bool ContainsWorldLocation(const FVector& WorldLocation) const;

	// Technical server/importer identifier. Reimporting a map updates this field.
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Map", meta = (DisplayName = "Map Identifier Name"))
	FString MapId;

	// Numeric identifier from server locale map/index. Quests use this through pc.get_map_index().
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Map", meta = (DisplayName = "Map ID (Index)"))
	int32 MapIndex = 0;

	// Player-facing map name populated from locale/en/locale_game.txt during import. It remains
	// editable for map-specific overrides.
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Map|Appearance")
	FString MapName;

	// Non-spatial map music. Any sound type is accepted and replayed continuously.
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Map|Appearance")
	TObjectPtr<USoundBase> DefaultMusic;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Map|Appearance")
	FMT2MapEnvironmentSettings Environment;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Map")
	FIntPoint MapCells = FIntPoint::ZeroValue;

	UPROPERTY(VisibleAnywhere, Category = "Map|Attributes")
	FMT2MapAttributes Attributes;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Map")
	FVector2D WorldMin = FVector2D::ZeroVector;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Map")
	FVector2D WorldMax = FVector2D::ZeroVector;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Minimap")
	TArray<FMT2MinimapTile> MinimapTiles;

	// Local map coordinates imported from the server Town.txt file.
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Map|Spawn")
	FVector2D DefaultTownSpawn = FVector2D::ZeroVector;

	// Shinsoo, Chunjo and Jinno positions, in that order. Missing entries use DefaultTownSpawn.
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Map|Spawn")
	TArray<FVector2D> EmpireTownSpawns;

private:
	void ApplyEnvironmentComponents();

	UFUNCTION()
	void RestartDefaultMusic();

	UPROPERTY(VisibleAnywhere, Category = "Map|Environment")
	TObjectPtr<USceneComponent> SceneRoot;

	UPROPERTY(VisibleAnywhere, Category = "Map|Environment")
	TObjectPtr<UDirectionalLightComponent> EnvironmentDirectionalLight;

	UPROPERTY(VisibleAnywhere, Category = "Map|Environment")
	TObjectPtr<USkyLightComponent> EnvironmentSkyLight;

	UPROPERTY(VisibleAnywhere, Category = "Map|Environment")
	TObjectPtr<UExponentialHeightFogComponent> EnvironmentFog;

	UPROPERTY(VisibleAnywhere, Category = "Map|Appearance")
	TObjectPtr<UAudioComponent> MusicComponent;
};
