/*

- Copyright © 2026 Castellese Brian Vincenzo.
- Licensed under the PolyForm Noncommercial License 1.0.0.
- Commercial use and resale require separate written permission.
- See LICENSE for the complete terms.

*/

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "Items/MT2ItemTypes.h"
#include "Player/MT2PlayerTypes.h"
#include "MT2ItemTemplate.generated.h"

class UMT2ItemTooltipWidget;
class UMT2Item;
class UMT2LootTable;
class UMaterialInterface;
class USkeletalMesh;
class UStaticMesh;
class UTexture2D;

USTRUCT(BlueprintType)
struct METIN2_API FMT2ArmorMaterialOverride
{
	GENERATED_BODY()

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Armor", meta = (ClampMin = "0"))
	int32 MaterialSlotIndex = INDEX_NONE;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Armor")
	TSoftObjectPtr<UMaterialInterface> Material;
};

USTRUCT(BlueprintType)
struct METIN2_API FMT2ArmorMeshVariant
{
	GENERATED_BODY()

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Armor")
	EMT2CharacterRace Race = EMT2CharacterRace::Warrior;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Armor")
	EMT2CharacterSex Sex = EMT2CharacterSex::Male;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Armor")
	TSoftObjectPtr<USkeletalMesh> Mesh;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Armor")
	TArray<FMT2ArmorMaterialOverride> MaterialOverrides;
};

USTRUCT(BlueprintType)
struct METIN2_API FMT2HairMeshVariant
{
	GENERATED_BODY()

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Hair")
	EMT2CharacterRace Race = EMT2CharacterRace::Warrior;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Hair")
	EMT2CharacterSex Sex = EMT2CharacterSex::Male;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Hair")
	TSoftObjectPtr<USkeletalMesh> Mesh;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Hair")
	TSoftObjectPtr<UTexture2D> DiffuseTexture;
};

UCLASS(Abstract, Blueprintable)
class METIN2_API UMT2ItemTemplate : public UPrimaryDataAsset
{
	GENERATED_BODY()

public:
	virtual void PostLoad() override;

	UFUNCTION(BlueprintPure, Category = "Item")
	bool IsStackable() const { return (Flags & StackableFlag) != 0; }

	UFUNCTION(BlueprintPure, Category = "Item")
	int32 GetMaxStackSize() const { return IsStackable() ? MaximumStackSize : 1; }

	UFUNCTION(BlueprintPure, Category = "Item")
	FMT2ItemInstanceData MakeInstanceData(int32 Count = 1) const;

	// Gives subclasses a single, shared hook for per-instance data generated by inventory, loot
	// tables, and world drops.
	virtual void InitializeGeneratedInstance(FMT2ItemInstanceData& InOutData) const {}

	// Quest scripts occasionally inspect immutable proto values. Specialized templates expose only
	// values that have a named meaning; the base item deliberately owns no generic Value0..5 array.
	virtual int32 GetLegacyQuestValue(int32 Index) const { return 0; }

	UFUNCTION(BlueprintPure, Category = "Item|Flags")
	bool HasItemFlag(int32 ItemFlag) const { return (Flags & ItemFlag) != 0; }

	// The tooltip widget class used when this item is hovered. Uses the designer override if set,
	// otherwise the native per-type default. Subclasses return their family's default class.
	TSubclassOf<UMT2ItemTooltipWidget> ResolveTooltipClass() const;

	// Native default tooltip class for this item family; overridden per template subclass.
	virtual TSubclassOf<UMT2ItemTooltipWidget> GetDefaultTooltipClass() const;

	static constexpr int32 StackableFlag = 1 << 2;
	static constexpr int32 MaximumStackSize = 999;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Identity", meta = (ClampMin = "1"))
	int32 Vnum = 0;

	// Vnums in [Vnum, Vnum+VnumRange] resolve to this same item (old client SelectItemData ranges).
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Identity")
	int32 VnumRange = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Identity")
	FString InternalName;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Identity")
	FText DisplayName;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Identity", meta = (MultiLine = "true"))
	FText Description;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation")
	TSoftObjectPtr<UTexture2D> Icon;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation")
	TSoftObjectPtr<UStaticMesh> WorldMesh;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Inventory", meta = (ClampMin = "1"))
	int32 InventorySize = 1;

	// Imported display value. Runtime stackability is authoritatively derived from ITEM_FLAG_STACKABLE.
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Inventory", meta = (ClampMin = "1", ClampMax = "999"))
	int32 MaxStackSize = 1;

	// item_proto WEIGHT; carried but unused (the old game never enforced weight either).
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Inventory")
	int32 Weight = 0;

	// 40250 TItemTable dwIBuyItemPrice: what shops charge the player.
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Economy", meta = (ClampMin = "0"))
	int64 BuyPrice = 0;

	// 40250 TItemTable dwISellItemPrice: what shops pay the player.
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Economy", meta = (ClampMin = "0"))
	int64 SellPrice = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Flags",
		meta = (Bitmask, BitmaskEnum = "/Script/Metin2.EMT2ItemAntiFlag"))
	int32 AntiFlags = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Flags",
		meta = (Bitmask, BitmaskEnum = "/Script/Metin2.EMT2ItemFlag"))
	int32 Flags = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Flags",
		meta = (Bitmask, BitmaskEnum = "/Script/Metin2.EMT2ItemImmuneFlag"))
	int32 ImmuneFlags = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Refinement")
	int32 RefinedVnum = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Refinement")
	int32 RefineSet = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Refinement")
	int32 PreviousRefinedVnum = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Refinement",
		meta = (ClampMin = "0", ClampMax = "9"))
	int32 RefinementLevel = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Refinement")
	FMT2RefinementRecipe RefinementRecipe;

	// item_proto MAGIC_PCT: chance to roll magic attributes when acquired; not wired yet.
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Refinement")
	int32 AlterToMagicItemPercent = 0;

	// item_proto aApplies[3]: stat bonuses applied while equipped (EApplyTypes ordinal + value).
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Stats")
	TArray<FMT2ItemApply> Applies;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Stats")
	TArray<FMT2ItemLimit> Limits;

	// Mutable defaults copied into every newly-created item instance, including authored Metin
	// sockets and intrinsic instance bonuses.
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Stats")
	FMT2ItemInstanceData DefaultInstanceData;

	// Optional designer override: point a template at a bespoke tooltip Blueprint. Empty = the
	// native per-type default from GetDefaultTooltipClass().
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation")
	TSubclassOf<UMT2ItemTooltipWidget> TooltipWidgetOverride;

private:
	// One-load migration for generated item assets imported before DefaultInstanceData existed.
	UPROPERTY()
	TArray<int32> Sockets_DEPRECATED;
};

UCLASS(Abstract, Blueprintable)
class METIN2_API UMT2ItemEquipmentTemplate : public UMT2ItemTemplate
{
	GENERATED_BODY()

public:
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Equipment",
		meta = (Bitmask, BitmaskEnum = "/Script/Metin2.EMT2ItemWearFlag"))
	int32 WearFlags = 0;

	// The old server calls this GAIN_SOCKET_PCT, but uses it as the initial silver-socket count.
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Equipment|Sockets",
		meta = (ClampMin = "0", ClampMax = "3"))
	int32 DefaultSilverSocketCount = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Equipment|Sockets",
		meta = (ClampMin = "0", ClampMax = "3"))
	int32 DefaultGoldSocketCount = 0;

	// Old item_proto addon_type. -1 enables the paired average/skill-damage weapon formula.
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Equipment|Bonuses")
	int32 BonusAddonType = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Equipment|Presentation")
	int32 Specular = 0;
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemWeaponTemplate : public UMT2ItemEquipmentTemplate
{
	GENERATED_BODY()

public:
	virtual TSubclassOf<UMT2ItemTooltipWidget> GetDefaultTooltipClass() const override;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Weapon")
	int32 WeaponSubType = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Weapon|Damage")
	int32 MagicDamageMin = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Weapon|Damage")
	int32 MagicDamageMax = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Weapon|Damage")
	int32 PhysicalDamageMin = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Weapon|Damage")
	int32 PhysicalDamageMax = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Weapon|Damage")
	int32 RefinementDamage = 0;

	UFUNCTION(BlueprintPure, Category = "Weapon|Damage")
	int32 GetPhysicalDamageMin() const
	{
		return PhysicalDamageMin + RefinementDamage;
	}

	UFUNCTION(BlueprintPure, Category = "Weapon|Damage")
	int32 GetPhysicalDamageMax() const
	{
		return PhysicalDamageMax + RefinementDamage;
	}

	UFUNCTION(BlueprintPure, Category = "Weapon|Damage")
	int32 GetMagicDamageMin() const
	{
		return MagicDamageMin + RefinementDamage;
	}

	UFUNCTION(BlueprintPure, Category = "Weapon|Damage")
	int32 GetMagicDamageMax() const
	{
		return MagicDamageMax + RefinementDamage;
	}

	UFUNCTION(BlueprintPure, Category = "Weapon|Damage")
	int32 GetAdditionalDamage() const
	{
		return RefinementDamage;
	}
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemArmorTemplate : public UMT2ItemEquipmentTemplate
{
	GENERATED_BODY()

public:
	virtual TSubclassOf<UMT2ItemTooltipWidget> GetDefaultTooltipClass() const override;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Armor")
	int32 ArmorSubType = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Armor|Stats")
	int32 Defense = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Armor|Stats")
	int32 RefinementDefense = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Armor|Visual")
	int32 ArmorShapeId = 0;

	// Unlike weapons (attached as a separate static mesh), body armor replaces the character's whole
	// skeletal mesh - the old client does the same per-race/gender body swap on equip.
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Armor")
	TSoftObjectPtr<USkeletalMesh> ArmorMesh;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Armor")
	TArray<FMT2ArmorMeshVariant> ArmorMeshVariants;

	TSoftObjectPtr<USkeletalMesh> ResolveArmorMesh(const FMT2CharacterAppearance& Appearance) const
	{
		if (const FMT2ArmorMeshVariant* Variant = ArmorMeshVariants.FindByPredicate(
			[&Appearance](const FMT2ArmorMeshVariant& Candidate)
			{
				return Candidate.Race == Appearance.Race && Candidate.Sex == Appearance.Sex;
			}))
		{
			return Variant->Mesh;
		}
		return ArmorMesh;
	}

	const FMT2ArmorMeshVariant* ResolveArmorVariant(const FMT2CharacterAppearance& Appearance) const
	{
		return ArmorMeshVariants.FindByPredicate(
			[&Appearance](const FMT2ArmorMeshVariant& Candidate)
			{
				return Candidate.Race == Appearance.Race && Candidate.Sex == Appearance.Sex;
			});
	}
};

UCLASS(Abstract, Blueprintable)
class METIN2_API UMT2ItemConsumableTemplate : public UMT2ItemTemplate
{
	GENERATED_BODY()
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemUseTemplate : public UMT2ItemConsumableTemplate
{
	GENERATED_BODY()

public:
	virtual TSubclassOf<UMT2ItemTooltipWidget> GetDefaultTooltipClass() const override;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Use")
	int32 UseSubType = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Use|Recovery")
	int32 HealthRecovery = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Use|Recovery")
	int32 ManaRecovery = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Use|Recovery")
	int32 HealthRecoveryPercent = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Use|Recovery")
	int32 ManaRecoveryPercent = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Use|Buff")
	EMT2ItemBonusType GrantedBonus = EMT2ItemBonusType::None;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Use|Buff")
	int32 GrantedBonusValue = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Use|Buff")
	int32 BuffDurationSeconds = 0;

	// USE_AFFECT Value0. Multiple data-driven consumables may grant the same apply type under
	// different affect IDs, so keep the identity separate from the bonus enum.
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Use|Buff")
	int32 AffectType = 0;
};

UENUM(BlueprintType)
enum class EMT2AutoRecoveryResource : uint8
{
	Health,
	Mana
};

// Old USE_SPECIAL automatic potion. One item owns a finite recovery reservoir and toggles on/off;
// unlike normal potions, using it does not consume the item until the reservoir is empty.
UCLASS(Blueprintable)
class METIN2_API UMT2ItemAutoRecoveryTemplate : public UMT2ItemUseTemplate
{
	GENERATED_BODY()

public:
	virtual void InitializeGeneratedInstance(FMT2ItemInstanceData& InOutData) const override;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Automatic Recovery")
	EMT2AutoRecoveryResource Resource = EMT2AutoRecoveryResource::Health;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Automatic Recovery", meta = (ClampMin = "1"))
	int32 RecoveryCapacity = 0;
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemRefinementScrollTemplate : public UMT2ItemUseTemplate
{
	GENERATED_BODY()

public:
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Refinement",
		meta = (ClampMin = "0", ClampMax = "100", Units = "%"))
	int32 AdditionalSuccessPercent = 10;
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemAutoUseTemplate : public UMT2ItemConsumableTemplate
{
	GENERATED_BODY()

public:
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Use")
	int32 AutoUseSubType = 0;
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemMaterialTemplate : public UMT2ItemTemplate
{
	GENERATED_BODY()

public:
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Material")
	int32 MaterialSubType = 0;
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemSpecialTemplate : public UMT2ItemTemplate
{
	GENERATED_BODY()
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemToolTemplate : public UMT2ItemTemplate
{
	GENERATED_BODY()
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemLotteryTemplate : public UMT2ItemTemplate
{
	GENERATED_BODY()
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemGoldTemplate : public UMT2ItemTemplate
{
	GENERATED_BODY()
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemMetinStoneTemplate : public UMT2ItemTemplate
{
	GENERATED_BODY()

public:
	// METIN_NORMAL=0 may enter silver or gold; METIN_GOLD=1 requires a gold socket.
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Metin Stone")
	int32 MetinSubType = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Metin Stone",
		meta = (Bitmask, BitmaskEnum = "/Script/Metin2.EMT2ItemWearFlag"))
	int32 CompatibleWearFlags = 0;

	// Value5 in the original item_proto. Equipment cannot contain two stones in one category.
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Metin Stone")
	int32 StoneCategory = 0;

	// Minimum socket grade accepted by the original comparison (silver=1, gold=2).
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Metin Stone",
		meta = (ClampMin = "1", ClampMax = "2"))
	int32 RequiredSocketGrade = 1;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Metin Stone",
		meta = (ClampMin = "0.0", ClampMax = "100.0"))
	float AttachmentSuccessPercent = 30.0f;
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemContainerTemplate : public UMT2ItemTemplate
{
	GENERATED_BODY()
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemLootCrateTemplate : public UMT2ItemContainerTemplate
{
	GENERATED_BODY()

public:
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Loot Crate")
	TSubclassOf<UMT2LootTable> LootTable;

	// Empty means right-click opens the crate. Set means that exact item template must be moved onto
	// the crate; one key and one crate are consumed atomically.
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Loot Crate")
	TSubclassOf<UMT2ItemTemplate> RequiredKeyTemplate;
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemFishTemplate : public UMT2ItemTemplate
{
	GENERATED_BODY()
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemRodTemplate : public UMT2ItemToolTemplate
{
	GENERATED_BODY()

public:
	virtual int32 GetLegacyQuestValue(int32 Index) const override
	{
		switch (Index)
		{
		case 0: return FishingDelayTenths;
		case 2: return ImprovementPointsRequired;
		case 3: return RefinementSuccessPercent;
		default: return 0;
		}
	}

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Fishing")
	int32 FishingDelayTenths = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Fishing")
	int32 ImprovementPointsRequired = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Fishing")
	int32 RefinementSuccessPercent = 0;
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemResourceTemplate : public UMT2ItemMaterialTemplate
{
	GENERATED_BODY()
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemCampfireTemplate : public UMT2ItemTemplate
{
	GENERATED_BODY()
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemUniqueTemplate : public UMT2ItemEquipmentTemplate
{
	GENERATED_BODY()

public:
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Unique")
	int32 UniqueSubType = 0;
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemSkillBookTemplate : public UMT2ItemConsumableTemplate
{
	GENERATED_BODY()

public:
	virtual void InitializeGeneratedInstance(FMT2ItemInstanceData& InOutData) const override;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Skill Book")
	int32 SkillVnum = 0;
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemQuestTemplate : public UMT2ItemTemplate
{
	GENERATED_BODY()
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemPolymorphTemplate : public UMT2ItemConsumableTemplate
{
	GENERATED_BODY()
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemTreasureBoxTemplate : public UMT2ItemLootCrateTemplate
{
	GENERATED_BODY()
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemTreasureKeyTemplate : public UMT2ItemTemplate
{
	GENERATED_BODY()
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemSkillForgetTemplate : public UMT2ItemConsumableTemplate
{
	GENERATED_BODY()
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemGiftBoxTemplate : public UMT2ItemLootCrateTemplate
{
	GENERATED_BODY()
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemPickTemplate : public UMT2ItemToolTemplate
{
	GENERATED_BODY()

public:
	virtual int32 GetLegacyQuestValue(int32 Index) const override
	{
		return Index == 2 ? ImprovementPointsRequired
			: (Index == 3 ? RefinementSuccessPercent : 0);
	}

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Mining")
	int32 ImprovementPointsRequired = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Mining")
	int32 RefinementSuccessPercent = 0;
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemHairTemplate : public UMT2ItemEquipmentTemplate
{
	GENERATED_BODY()
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemTotemTemplate : public UMT2ItemEquipmentTemplate
{
	GENERATED_BODY()
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemBlendTemplate : public UMT2ItemConsumableTemplate
{
	GENERATED_BODY()
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemCostumeTemplate : public UMT2ItemEquipmentTemplate
{
	GENERATED_BODY()

public:
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Costume")
	int32 CostumeSubType = 0;

	// COSTUME_HAIR stores the old client's race-data HairIndex in item_proto Value3.
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Costume|Hair")
	int32 HairShapeId = 0;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Costume|Hair")
	TArray<FMT2HairMeshVariant> HairMeshVariants;

	const FMT2HairMeshVariant* ResolveHairVariant(
		const FMT2CharacterAppearance& Appearance) const
	{
		return HairMeshVariants.FindByPredicate(
			[&Appearance](const FMT2HairMeshVariant& Candidate)
			{
				return Candidate.Race == Appearance.Race && Candidate.Sex == Appearance.Sex;
			});
	}
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemDragonSoulTemplate : public UMT2ItemEquipmentTemplate
{
	GENERATED_BODY()
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemSpecialDragonSoulTemplate : public UMT2ItemDragonSoulTemplate
{
	GENERATED_BODY()
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemExtractTemplate : public UMT2ItemTemplate
{
	GENERATED_BODY()
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemSecondaryCoinTemplate : public UMT2ItemTemplate
{
	GENERATED_BODY()
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemRingTemplate : public UMT2ItemEquipmentTemplate
{
	GENERATED_BODY()
public:
	virtual TSubclassOf<UMT2ItemTooltipWidget> GetDefaultTooltipClass() const override;
};

UCLASS(Blueprintable)
class METIN2_API UMT2ItemBeltTemplate : public UMT2ItemEquipmentTemplate
{
	GENERATED_BODY()
public:
	virtual TSubclassOf<UMT2ItemTooltipWidget> GetDefaultTooltipClass() const override;
};
