/*

- Copyright © 2026 Castellese Brian Vincenzo.
- Licensed under the PolyForm Noncommercial License 1.0.0.
- Commercial use and resale require separate written permission.
- See LICENSE for the complete terms.

*/

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "MT2QuestTableAsset.generated.h"

// One entry of a converted Lua table. Nesting is stored flat - a node either holds a value or lists
// the indices of its children - because a directly recursive USTRUCT cannot be a UPROPERTY.
USTRUCT()
struct METIN2_API FMT2QuestTableNode
{
	GENERATED_BODY()

	UPROPERTY()
	bool bIsTable = false;

	UPROPERTY()
	bool bIsNumber = false;

	UPROPERTY()
	bool bIsBoolean = false;

	UPROPERTY()
	bool bIsNil = false;

	UPROPERTY()
	double Number = 0.0;

	UPROPERTY()
	FString Text;

	// Child node indices, in Lua order (index 1 in script == Children[0] here).
	UPROPERTY()
	TArray<int32> Children;

	// Named Lua fields (`setting.map_idx`, `setting.floor1_s.x`, ...).
	UPROPERTY()
	TMap<FName, int32> NamedChildren;
};

// One named table from the old scripts (`special.levelup_quest`, `special.questscroll`, ...).
USTRUCT()
struct METIN2_API FMT2QuestTable
{
	GENERATED_BODY()

	UPROPERTY()
	FName Name;

	// Nodes[0] is the root. Empty means the table failed to parse.
	UPROPERTY()
	TArray<FMT2QuestTableNode> Nodes;

	const FMT2QuestTableNode* GetNode(int32 NodeIndex) const
	{
		return Nodes.IsValidIndex(NodeIndex) ? &Nodes[NodeIndex] : nullptr;
	}

	// Lua indices are 1-based; this takes that script-facing index directly.
	int32 GetChildIndex(int32 NodeIndex, int32 LuaIndex) const
	{
		const FMT2QuestTableNode* Node = GetNode(NodeIndex);
		const int32 ChildSlot = LuaIndex - 1;
		return (Node && Node->Children.IsValidIndex(ChildSlot)) ? Node->Children[ChildSlot] : INDEX_NONE;
	}

	int32 GetNamedChildIndex(int32 NodeIndex, FName FieldName) const
	{
		const FMT2QuestTableNode* Node = GetNode(NodeIndex);
		const int32* ChildIndex = Node ? Node->NamedChildren.Find(FieldName) : nullptr;
		return ChildIndex ? *ChildIndex : INDEX_NONE;
	}
};

// Server map metadata required to resolve the old game's global pc.warp coordinates without
// hardcoding quest destinations. Generated from map/index and each map's Setting.txt.
USTRUCT()
struct METIN2_API FMT2QuestMapDefinition
{
	GENERATED_BODY()

	UPROPERTY()
	int32 MapIndex = 0;

	UPROPERTY()
	FString MapId;

	// Cooked Unreal world package corresponding to MapId. Client and server map names are not
	// always identical (for example, server map_n_threeway is imported from client map_a2).
	UPROPERTY()
	FString WorldPackagePath;

	UPROPERTY()
	FVector2D GlobalOrigin = FVector2D::ZeroVector;

	UPROPERTY()
	FVector2D WorldSize = FVector2D::ZeroVector;

	bool ContainsGlobalPosition(const FVector2D& Position) const
	{
		return Position.X >= GlobalOrigin.X && Position.Y >= GlobalOrigin.Y &&
			Position.X <= GlobalOrigin.X + WorldSize.X &&
			Position.Y <= GlobalOrigin.Y + WorldSize.Y;
	}

	FVector2D ToUnrealPosition(const FVector2D& GlobalPosition) const
	{
		return FVector2D(
			WorldSize.X - (GlobalPosition.X - GlobalOrigin.X),
			-(GlobalPosition.Y - GlobalOrigin.Y));
	}
};

// The constant tables the old quest scripts read (questlib.lua / locale.lua `special.*` definitions),
// generated by the quest importer. They are shared, read-only data: the scripts only ever index them.
UCLASS()
class METIN2_API UMT2QuestTableAsset : public UPrimaryDataAsset
{
	GENERATED_BODY()

public:
	UPROPERTY()
	TArray<FMT2QuestTable> Tables;

	UPROPERTY()
	TArray<FMT2QuestMapDefinition> Maps;

	// Quest ids listed by the server's locale_list at import time. An empty set keeps compatibility
	// with manually authored projects; a populated set is the authoritative imported quest manifest.
	UPROPERTY()
	TSet<FName> ActiveQuestIds;

	const FMT2QuestTable* FindTable(FName TableName) const
	{
		return Tables.FindByPredicate(
			[TableName](const FMT2QuestTable& Table) { return Table.Name == TableName; });
	}

	const FMT2QuestMapDefinition* FindMapByIndex(int32 MapIndex) const
	{
		return Maps.FindByPredicate(
			[MapIndex](const FMT2QuestMapDefinition& Map) { return Map.MapIndex == MapIndex; });
	}

	const FMT2QuestMapDefinition* FindMapById(const FString& MapId) const
	{
		auto Normalize = [](FString Value)
		{
			Value = Value.TrimStartAndEnd().ToLower();
			Value.ReplaceInline(TEXT("\\"), TEXT("/"));
			int32 Separator = INDEX_NONE;
			if (Value.FindLastChar(TEXT('/'), Separator)) Value.RightChopInline(Separator + 1);
			if (Value.FindChar(TEXT('.'), Separator)) Value.LeftInline(Separator);
			if (Value.StartsWith(TEXT("metin2_map_"))) Value.RightChopInline(11);
			else if (Value.StartsWith(TEXT("map_"))) Value.RightChopInline(4);
			return Value;
		};
		const FString NormalizedMapId = Normalize(MapId);
		return Maps.FindByPredicate([&MapId, &NormalizedMapId, &Normalize](const FMT2QuestMapDefinition& Map)
		{
			return Map.MapId.Equals(MapId, ESearchCase::IgnoreCase) ||
				Normalize(Map.MapId) == NormalizedMapId;
		});
	}

	const FMT2QuestMapDefinition* FindMapAtGlobalPosition(const FVector2D& Position) const
	{
		const FMT2QuestMapDefinition* BestMatch = nullptr;
		for (const FMT2QuestMapDefinition& Map : Maps)
		{
			if (Map.ContainsGlobalPosition(Position) &&
				(!BestMatch || Map.WorldSize.X * Map.WorldSize.Y <
					BestMatch->WorldSize.X * BestMatch->WorldSize.Y))
			{
				BestMatch = &Map;
			}
		}
		return BestMatch;
	}

	// Path the importer writes to and the runtime loads from.
	static const TCHAR* GetAssetPath()
	{
		return TEXT("/Game/Quests/DA_MT2QuestTables.DA_MT2QuestTables");
	}
};
